### ISSUE TITLE
El proceso de comprar debería terminar con un mensaje mostrando la información de contacto del ofertante

### ISSUE THREAD

**Issue by nitanilla** [UwUnsaac/Ecommerce-Reactjs#15]
![image](https://user-images.githubusercontent.com/1106435/109444707-d57e8680-7a0b-11eb-8d0e-031462b864ab.png)

**Comment by SHJAndre** [comment]
- [x] Añadir contacto en la informacion mostrada
- [x] Eliminar la opcion de comprar
- [x] Cambiar enfoce Bolsa -> Favoritos

**Comment by nitanilla** [comment]
#14 ok
